services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  dev:
    build: .
    container_name: cs242
    working_dir: /app
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # Tell your Python script where to look
      - ES_URL=http://es-node:9200
    command: tail -f /dev/null